In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('/content/mushroom.csv')
data.head()

Unnamed: 0   class cap-shape cap-surface cap-color  bruises    odor  \
0           0  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND   
1           1  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND   
2           2  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND   
3           3  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND   
4           4  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND   

  gill-attachment gill-spacing gill-size  ... stalk-surface-below-ring  \
0            FREE      CROWDED    NARROW  ...                   SMOOTH   
1            FREE      CROWDED    NARROW  ...                   SMOOTH   
2            FREE      CROWDED    NARROW  ...                   SMOOTH   
3            FREE      CROWDED    NARROW  ...                   SMOOTH   
4            FREE      CROWDED    NARROW  ...                   SMOOTH   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                  WHITE                  WHITE   PARTIAL      WHITE   
1                  WHITE                  WHITE   PARTIAL      WHITE   
2                  WHITE                  WHITE   PARTIAL      WHITE   
3                  WHITE                  WHITE   PARTIAL      WHITE   
4                  WHITE                  WHITE   PARTIAL      WHITE   

  ring-number ring-type spore-print-color population habitat  
0         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
1         ONE   PENDANT             BROWN    SEVERAL   WOODS  
2         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
3         ONE   PENDANT             BROWN    SEVERAL   WOODS  
4         ONE   PENDANT            PURPLE    SEVERAL   WOODS  

[5 rows x 24 columns]

In [ ]:
data.columns

Index(['Unnamed: 0', 'class', 'cap-shape', 'cap-surface', 'cap-color',
       'bruises', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size',
       'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [ ]:
data.rename(columns={'stalk-surface-above-ring':'above-ring', 'stalk-surface-below-ring':'below-ring',
                     'stalk-color-above-ring':'color-above', 'stalk-color-below-ring':'color-below',
                     'spore-print-color':'spore-color'}, inplace=True)

In [ ]:
a = []
for i in data:
  a.append(i.replace('-','_'))


In [ ]:
data.tail()

class cap_shape cap_surface  \
8412                                             EDIBLE   KNOBBED      SMOOTH   
8413                                             EDIBLE   KNOBBED      SMOOTH   
8414                                             EDIBLE   KNOBBED      SMOOTH   
8415                                             EDIBLE   KNOBBED      SMOOTH   
8416  ----------------------------------------------...       NaN         NaN   

     cap_color bruises  odor gill_attachment gill_spacing gill_size  \
8412     BROWN      NO  NONE        ATTACHED        CLOSE     BROAD   
8413     BROWN      NO  NONE        ATTACHED        CLOSE     BROAD   
8414     BROWN      NO  NONE        ATTACHED        CLOSE     BROAD   
8415     BROWN      NO  NONE        ATTACHED        CLOSE     BROAD   
8416       NaN     NaN   NaN             NaN          NaN       NaN   

     gill_color  ... below_ring color_above color_below veil_type veil_color  \
8412      BROWN  ...     SMOOTH      ORANGE      ORANGE   PARTIAL      BROWN   
8413      BROWN  ...     SMOOTH      ORANGE      ORANGE   PARTIAL      BROWN   
8414      BROWN  ...     SMOOTH      ORANGE      ORANGE   PARTIAL      BROWN   
8415      BROWN  ...     SMOOTH      ORANGE      ORANGE   PARTIAL      BROWN   
8416        NaN  ...        NaN         NaN         NaN       NaN        NaN   

     ring_number ring_type spore_color population habitat  
8412         ONE   PENDANT      ORANGE    SEVERAL  LEAVES  
8413         ONE   PENDANT      ORANGE  CLUSTERED  LEAVES  
8414         ONE   PENDANT        BUFF    SEVERAL  LEAVES  
8415         ONE   PENDANT        BUFF  CLUSTERED  LEAVES  
8416         NaN       NaN         NaN        NaN     NaN  

[5 rows x 23 columns]

In [ ]:
# data = data.iloc[:-1]

In [1]:
# data.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
data.columns

Index(['class', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'above_ring', 'below_ring', 'color_above',
       'color_below', 'veil_type', 'veil_color', 'ring_number', 'ring_type',
       'spore_color', 'population', 'habitat'],
      dtype='object')

In [ ]:
data.isnull().sum()

class              0
cap_shape          1
cap_surface        1
cap_color          1
bruises            1
odor               1
gill_attachment    1
gill_spacing       1
gill_size          1
gill_color         1
stalk_shape        1
stalk_root         1
above_ring         1
below_ring         1
color_above        1
color_below        1
veil_type          1
veil_color         1
ring_number        1
ring_type          1
spore_color        1
population         1
habitat            1
dtype: int64

In [ ]:
data.drop(columns=['habitat'], inplace=True)

In [ ]:
# will probably just use fillna in train_test data while scaling since doing for each for only 1 null value seems meaningless

In [ ]:
num_cols = data.select_dtypes(include=[float,int]).columns
num_cols

Index([], dtype='object')

In [ ]:
#NO outlier handling going for encoding all columns

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
encoder = LabelEncoder()
onehot = OneHotEncoder()
ordinal = OrdinalEncoder()

In [ ]:
data.head()

class cap_shape cap_surface cap_color  bruises    odor gill_attachment  \
0  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
1  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
2  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
3  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
4  EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   

  gill_spacing gill_size gill_color  ... above_ring below_ring color_above  \
0      CROWDED    NARROW      WHITE  ...     SMOOTH     SMOOTH       WHITE   
1      CROWDED    NARROW      WHITE  ...     SMOOTH     SMOOTH       WHITE   
2      CROWDED    NARROW       PINK  ...     SMOOTH     SMOOTH       WHITE   
3      CROWDED    NARROW       PINK  ...     SMOOTH     SMOOTH       WHITE   
4      CROWDED    NARROW      BROWN  ...     SMOOTH     SMOOTH       WHITE   

  color_below veil_type veil_color ring_number ring_type spore_color  \
0       WHITE   PARTIAL      WHITE         ONE   PENDANT      PURPLE   
1       WHITE   PARTIAL      WHITE         ONE   PENDANT       BROWN   
2       WHITE   PARTIAL      WHITE         ONE   PENDANT      PURPLE   
3       WHITE   PARTIAL      WHITE         ONE   PENDANT       BROWN   
4       WHITE   PARTIAL      WHITE         ONE   PENDANT      PURPLE   

  population  
0    SEVERAL  
1    SEVERAL  
2    SEVERAL  
3    SEVERAL  
4    SEVERAL  

[5 rows x 22 columns]

In [ ]:
data.columns

Index(['class', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'above_ring', 'below_ring', 'color_above',
       'color_below', 'veil_type', 'veil_color', 'ring_number', 'ring_type',
       'spore_color', 'population'],
      dtype='object')

In [ ]:
data.rename(columns={'class':'type'}, inplace=True)

In [ ]:
# Did classification instead of encoding to convert target column
data['type_binary'] = data['type'].apply(lambda x:0 if x=='EDIBLE' else 1)

In [ ]:
# One hot encoding not possible since so many columns so going with Label only
# not using ordinal since not sure about data heirarchy

data['cap_shape'] = encoder.fit_transform(data['cap_shape'])
data['cap_surface'] = encoder.fit_transform(data['cap_surface'])
data['cap_color'] = encoder.fit_transform(data['cap_color'])
data['bruises'] = encoder.fit_transform(data['bruises'])
data['gill_attachment'] = encoder.fit_transform(data['gill_attachment'])
data['gill_spacing'] = encoder.fit_transform(data['gill_spacing'])
data['gill_size'] = encoder.fit_transform(data['gill_size'])
data['gill_color'] = encoder.fit_transform(data['gill_color'])
data['stalk_shape'] = encoder.fit_transform(data['stalk_shape'])
data['stalk_root'] = encoder.fit_transform(data['stalk_root'])
data['veil_type'] = encoder.fit_transform(data['veil_type'])
data['veil_color'] = encoder.fit_transform(data['veil_color'])
data['ring_number'] = encoder.fit_transform(data['ring_number'])
data['ring_type'] = encoder.fit_transform(data['ring_type'])
data['spore_color'] = encoder.fit_transform(data['spore_color'])
data['population'] = encoder.fit_transform(data['population'])
data['above_ring'] = encoder.fit_transform(data['above_ring'])
data['below_ring'] = encoder.fit_transform(data['below_ring'])



In [ ]:
data.columns

Index(['type', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'above_ring', 'below_ring', 'color_above',
       'color_below', 'veil_type', 'veil_color', 'ring_number', 'ring_type',
       'spore_color', 'population', 'type_binary'],
      dtype='object')

In [ ]:
data.drop(columns=['type'], inplace=True)

In [ ]:
data['odor'] = encoder.fit_transform(data['odor'])
data['color_above'] = encoder.fit_transform(data['color_above'])
data['color_below'] = encoder.fit_transform(data['color_below'])

In [ ]:
data.head()

cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0          2            3          8        0     0                1   
1          2            3          8        0     0                1   
2          2            3          8        0     0                1   
3          2            3          8        0     0                1   
4          2            3          8        0     0                1   

   gill_spacing  gill_size  gill_color  stalk_shape  ...  below_ring  \
0             1          1          10            1  ...           3   
1             1          1          10            1  ...           3   
2             1          1           7            1  ...           3   
3             1          1           7            1  ...           3   
4             1          1           1            1  ...           3   

   color_above  color_below  veil_type  veil_color  ring_number  ring_type  \
0            7            7          0           2            1          4   
1            7            7          0           2            1          4   
2            7            7          0           2            1          4   
3            7            7          0           2            1          4   
4            7            7          0           2            1          4   

   spore_color  population  type_binary  
0            6           4            0  
1            1           4            0  
2            6           4            0  
3            1           4            0  
4            6           4            0  

[5 rows x 22 columns]

In [ ]:
X = data.drop(columns=['type_binary'])
Y = data['type_binary']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Not required
Y_train_log = np.log1p(Y_train)
Y_test_log = np.log1p(Y_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [ ]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score

In [ ]:
confusion_matrix(Y_test,y_pred)

array([[883,  34],
       [ 68, 699]])

In [ ]:
accuracy_score(Y_test,y_pred)

0.9394299287410927

In [ ]:
precision_score(Y_test,y_pred)

0.9536152796725784

In [ ]:
f1_score(Y_test,y_pred)

0.932

In [ ]:
recall_score(Y_test,y_pred)

0.9113428943937418

In [ ]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       917
           1       0.95      0.91      0.93       767

    accuracy                           0.94      1684
   macro avg       0.94      0.94      0.94      1684
weighted avg       0.94      0.94      0.94      1684



In [ ]:
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate , thresholds = roc_curve(Y_test,y_pred)
auc_score = auc(false_positive_rate, true_positive_rate)

In [ ]:
auc_score

np.float64(0.9371327340016693)

In [ ]:
false_positive_rate, true_positive_rate , thresholds = roc_curve(Y_test,y_pred)
false_positive_rate

array([0.        , 0.03707743, 1.        ])

In [ ]:
true_positive_rate

array([0.        , 0.91134289, 1.        ])